import { readFile, writeFile, readdir } from "node:fs/promises";
import { resolve, join } from "node:path";
import {
  addBacklog,
  listBacklog,
  updateBacklog,
  archiveDoneBacklog,
  listArchive,
  type BacklogRow,
  type BacklogStatus,
} from "../supabase.js";
import { currentProjectId, slugify } from "../project.js";
import { basename } from "node:path";

export type BacklogAction =
  | { action: "add"; title: string; priority?: number; notes?: string; project_id?: string }
  | { action: "list"; status?: BacklogStatus | BacklogStatus[]; project_id?: string }
  | {
      action: "update";
      id: number;
      title?: string;
      status?: BacklogStatus;
      priority?: number;
      notes?: string;
    }
  | { action: "prune_done"; project_id?: string }
  | { action: "archive_list"; project_id?: string; limit?: number }
  | { action: "session_end"; project_id?: string };

/** Lowest priority number wins (1 = highest). Ties broken by oldest-first. */
function pickNextTask(rows: BacklogRow[]): BacklogRow | null {
  if (rows.length === 0) return null;
  return [...rows].sort(
    (a, b) => a.priority - b.priority || Date.parse(a.created_at) - Date.parse(b.created_at),
  )[0];
}

const PROGRESS_HEADER = "### 🚀 Recent Progress";

// ─── Living architecture sync ────────────────────────────────────────────

const ARCH_IGNORE = new Set([
  "node_modules",
  ".git",
  "dist",
  "build",
  "backups",
  ".next",
  ".nuxt",
  ".cache",
  ".turbo",
  "coverage",
  "__pycache__",
]);

const ARCH_HIDDEN_ALLOWLIST = new Set([
  ".env.example",
  ".gitignore",
  ".mcp.json",
  ".github",
  ".claude",
]);

const ARCH_MAX_DEPTH = 3;
const ARCH_MAX_CHILDREN = 25;

type ArchNode = {
  name: string;
  type: "dir" | "file";
  children?: ArchNode[];
  truncated?: number;
};

async function scanTree(dir: string, depth: number): Promise<ArchNode> {
  const entries = await readdir(dir, { withFileTypes: true });
  const filtered = entries.filter((e) => {
    if (ARCH_IGNORE.has(e.name)) return false;
    if (e.name.startsWith(".") && !ARCH_HIDDEN_ALLOWLIST.has(e.name)) return false;
    return true;
  });
  filtered.sort((a, b) => {
    if (a.isDirectory() !== b.isDirectory()) return a.isDirectory() ? -1 : 1;
    return a.name.localeCompare(b.name);
  });
  const head = filtered.slice(0, ARCH_MAX_CHILDREN);
  const truncated = Math.max(0, filtered.length - ARCH_MAX_CHILDREN);

  const children: ArchNode[] = [];
  for (const e of head) {
    if (e.isDirectory() && depth < ARCH_MAX_DEPTH) {
      try {
        children.push(await scanTree(join(dir, e.name), depth + 1));
      } catch {
        children.push({ name: e.name, type: "dir" });
      }
    } else {
      children.push({ name: e.name, type: e.isDirectory() ? "dir" : "file" });
    }
  }
  return {
    name: basename(dir),
    type: "dir",
    children,
    truncated: truncated > 0 ? truncated : undefined,
  };
}

function mermaidSafeLabel(s: string): string {
  return s.replace(/"/g, "'").replace(/[\[\]]/g, "");
}

function renderArchMermaid(root: ArchNode): string {
  const lines = ["flowchart TD"];
  let counter = 0;
  const nextId = () => `n${counter++}`;

  function walk(node: ArchNode, parentId: string | null): void {
    const id = nextId();
    const label = node.type === "dir" ? `${node.name}/` : node.name;
    lines.push(`  ${id}["${mermaidSafeLabel(label)}"]`);
    if (parentId) lines.push(`  ${parentId} --> ${id}`);
    if (node.children) {
      for (const child of node.children) walk(child, id);
      if (node.truncated) {
        const tId = nextId();
        lines.push(`  ${tId}["… (${node.truncated} more)"]`);
        lines.push(`  ${id} --> ${tId}`);
      }
    }
  }
  walk(root, null);
  return lines.join("\n");
}

async function updateProjectArchitecture(projectId: string): Promise<{
  ok: boolean;
  path?: string;
  updated?: boolean;
  warning?: string;
}> {
  const docPath = resolve(process.cwd(), "project_file_architecture.md");
  try {
    const cwdSlug = slugify(basename(process.cwd()) || "default");
    if (cwdSlug !== projectId) {
      return {
        ok: true,
        path: docPath,
        updated: false,
        warning: `Architecture sync skipped — cwd project '${cwdSlug}' does not match session_end project_id '${projectId}'.`,
      };
    }

    const tree = await scanTree(process.cwd(), 0);
    const mermaid = renderArchMermaid(tree);
    const newBlock = ["```mermaid", mermaid, "```"].join("\n");

    let current = "";
    try {
      current = await readFile(docPath, "utf8");
    } catch {
      // file absent — we'll create it below
    }

    let updated: string;
    const mermaidBlockRe = /```mermaid[\s\S]*?```/;
    if (mermaidBlockRe.test(current)) {
      // Only replace the first mermaid block; leave any human-authored prose intact.
      updated = current.replace(mermaidBlockRe, newBlock);
    } else {
      const header = [
        `# Project File Architecture — ${projectId}`,
        "",
        `> Auto-generated by \`manage_backlog({ action: "session_end" })\`.`,
        `> Last sync: ${new Date().toISOString()}`,
        "",
        "Edit the header or prose freely; the tool only overwrites the Mermaid block.",
        "",
        "## Tree",
        "",
      ].join("\n");
      updated = current.trim()
        ? current.trimEnd() + "\n\n" + header + newBlock + "\n"
        : header + newBlock + "\n";
    }

    await writeFile(docPath, updated, "utf8");
    return { ok: true, path: docPath, updated: true };
  } catch (e) {
    return {
      ok: false,
      path: docPath,
      warning: `Architecture sync failed: ${(e as Error).message}`,
    };
  }
}

/**
 * Self-documenting session handover: rewrite or append the "Recent Progress"
 * section of the project's local README.md with the last 5 archived tasks.
 * Never throws — failures are returned as a warning so session_end still
 * completes the archive.
 */
async function updateLocalReadme(projectId: string): Promise<{
  ok: boolean;
  path?: string;
  updated?: boolean;
  warning?: string;
}> {
  const readmePath = resolve(process.cwd(), "README.md");
  try {
    // Safety: skip when the MCP server's cwd doesn't match the session_end
    // project — we'd otherwise overwrite the wrong repo's README.
    const cwdSlug = slugify(basename(process.cwd()) || "default");
    if (cwdSlug !== projectId) {
      return {
        ok: true,
        path: readmePath,
        updated: false,
        warning: `README sync skipped — cwd project '${cwdSlug}' does not match session_end project_id '${projectId}'.`,
      };
    }

    const archived = await listArchive(projectId, { limit: 5 });
    if (archived.length === 0) {
      return {
        ok: true,
        path: readmePath,
        updated: false,
        warning: "No archived tasks yet; nothing to write.",
      };
    }

    const bullets = archived
      .map((t) => `* [DONE] ${t.title} (archived at ${t.archived_at.slice(0, 10)}).`)
      .join("\n");
    const newSection = `${PROGRESS_HEADER}\n\n${bullets}`;

    let current = "";
    try {
      current = await readFile(readmePath, "utf8");
    } catch {
      // README may not exist yet; we'll create one.
    }

    let updated: string;
    const start = current.indexOf(PROGRESS_HEADER);
    if (start >= 0) {
      // Find the next markdown heading at level 1-3 after our section, or EOF.
      const tail = current.slice(start + PROGRESS_HEADER.length);
      const nextHeading = tail.match(/\n#{1,3}\s+\S/);
      const sectionEnd =
        nextHeading && nextHeading.index !== undefined
          ? start + PROGRESS_HEADER.length + nextHeading.index
          : current.length;
      updated = current.slice(0, start) + newSection + current.slice(sectionEnd);
    } else if (current.trim()) {
      updated = current.trimEnd() + "\n\n" + newSection + "\n";
    } else {
      updated = newSection + "\n";
    }

    await writeFile(readmePath, updated, "utf8");
    return { ok: true, path: readmePath, updated: true };
  } catch (e) {
    return {
      ok: false,
      path: readmePath,
      warning: `README sync failed: ${(e as Error).message}`,
    };
  }
}

export async function manageBacklog(args: BacklogAction) {
  const projectId = "project_id" in args && args.project_id ? args.project_id : currentProjectId;

  switch (args.action) {
    case "add": {
      const row = await addBacklog(projectId, args.title, {
        priority: args.priority,
        notes: args.notes,
      });
      return { action: "add", project_id: projectId, task: row };
    }

    case "list": {
      const rows = await listBacklog(projectId, { status: args.status });
      return { action: "list", project_id: projectId, count: rows.length, tasks: rows };
    }

    case "update": {
      const row = await updateBacklog(args.id, {
        title: args.title,
        status: args.status,
        priority: args.priority,
        notes: args.notes,
      });
      return { action: "update", task: row };
    }

    case "prune_done": {
      const archived = await archiveDoneBacklog(projectId);
      return { action: "prune_done", project_id: projectId, archived };
    }

    case "archive_list": {
      const rows = await listArchive(projectId, { limit: args.limit ?? 50 });
      return {
        action: "archive_list",
        project_id: projectId,
        count: rows.length,
        archived_tasks: rows,
      };
    }

    case "session_end": {
      const [todo, inProg, blocked, done] = await Promise.all([
        listBacklog(projectId, { status: "todo" }),
        listBacklog(projectId, { status: "in_progress" }),
        listBacklog(projectId, { status: "blocked" }),
        listBacklog(projectId, { status: "done" }),
      ]);

      const archived = await archiveDoneBacklog(projectId);

      // Living Documentation: README progress log + Mermaid file-tree.
      // Run in parallel — they touch different files.
      const [readmeSync, architectureSync] = await Promise.all([
        updateLocalReadme(projectId),
        updateProjectArchitecture(projectId),
      ]);

      const next = pickNextTask([...todo, ...inProg, ...blocked]);
      const nextTitle = next?.title ?? "backlog is empty — pick a new task";
      const resumePrompt =
        `search_memory({ query: "Active Backlog", project_id: "${projectId}" }) ` +
        `-> Reviewing pending tasks. Next up: ${nextTitle}.`;

      const humanSummary = [
        `Session ended.`,
        `${done.length} task${done.length === 1 ? "" : "s"} archived.`,
        `Remaining: ${todo.length} todo · ${inProg.length} in-progress · ${blocked.length} blocked.`,
        next ? `Next up: [P${next.priority}] ${next.title}` : `Backlog is empty.`,
      ].join(" ");

      return {
        action: "session_end",
        project_id: projectId,
        human_summary: humanSummary,
        progress_report: {
          completed_count: done.length,
          completed_titles: done.map((t) => t.title),
          remaining: {
            todo: todo.length,
            in_progress: inProg.length,
            blocked: blocked.length,
          },
        },
        archived,
        next_task: next
          ? {
              id: next.id,
              title: next.title,
              priority: next.priority,
              status: next.status,
              notes: next.notes,
            }
          : null,
        resume_prompt: resumePrompt,
        readme_sync: readmeSync,
        architecture_sync: architectureSync,
      };
    }
  }
}
